- name: Show version
  ansible.utils.cli_parse:
    command: show version
    parser:
      name: ansible.netcommon.pyats
  register: sh_version

- name: Collect Version Data
  ansible.builtin.set_fact:
    ios_version: "{{ sh_version ['parsed']['version']['xe_version'] }}"

- name: display value of show version
  ansible.builtin.debug:
    var: ios_version

- name: validate Show Version return_code state
  ansible.utils.validate:
    data: "{{ sh_version ['parsed'] }}"
    criteria:
      - "{{ lookup('file','../criteria/ios_version_criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  ignore_errors: true
  register: result

- name: IOS Version Validation
  ansible.builtin.debug:
    var: result
