---
- name: Health Check for dist-sw01 to dist-sw02
  hosts: dist-sw01
  gather_facts: false

  tasks:
  - name: Test reachability to dist-sw02 using mgmt vrf, size and df-bit
    cisco.nxos.nxos_ping:
      dest: "{{router_id }}"
      vrf: default
    register: result

  - name: Network Validation
    debug:
      var: result

    
    